### ISSUE TITLE
Thread 1 : program recieved signal : EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by sachalba** [akosma/bluewoki#1]
Hi , 
AFter downloading your source code , I was trying it on the simulator.  
When I press connect it searchs for devices.  While it is searching , I press cancel.  Then I press again connect and it gives the error : "Thread 1 : program recieved signal : EXC_BAD_ACCESS"
Any idea why ?
I think it is maybe because of autoreleasing and releasing...
Have a look ;)

**Comment by akosma** [comment]
Thanks for the report, I've updated the code, and mostly rewritten everything. This problem is gone now.
